// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fir.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fir::ap_const_logic_1 = sc_dt::Log_1;
const bool fir::ap_const_boolean_1 = true;
const sc_logic fir::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> fir::ap_const_lv10_35 = "110101";

fir::fir(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_output_V);
    sensitive << ( ap_start );
    sensitive << ( ret_V_fu_33_p2 );

    SC_METHOD(thread_output_V_ap_vld);
    sensitive << ( ap_start );

    SC_METHOD(thread_ret_V_fu_33_p0);
    sensitive << ( input_V );

    SC_METHOD(thread_ret_V_fu_33_p2);
    sensitive << ( ret_V_fu_33_p0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fir_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_V, "(port)output_V");
    sc_trace(mVcdFile, output_V_ap_vld, "(port)output_V_ap_vld");
    sc_trace(mVcdFile, input_V, "(port)input_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ret_V_fu_33_p0, "ret_V_fu_33_p0");
    sc_trace(mVcdFile, ret_V_fu_33_p2, "ret_V_fu_33_p2");
#endif

    }
    mHdltvinHandle.open("fir.hdltvin.dat");
    mHdltvoutHandle.open("fir.hdltvout.dat");
}

fir::~fir() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void fir::thread_ap_done() {
    ap_done = ap_start.read();
}

void fir::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void fir::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void fir::thread_output_V() {
    output_V = esl_sext<23,10>(ret_V_fu_33_p2.read());
}

void fir::thread_output_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        output_V_ap_vld = ap_const_logic_1;
    } else {
        output_V_ap_vld = ap_const_logic_0;
    }
}

void fir::thread_ret_V_fu_33_p0() {
    ret_V_fu_33_p0 = input_V.read();
}

void fir::thread_ret_V_fu_33_p2() {
    ret_V_fu_33_p2 = (!ret_V_fu_33_p0.read().is_01() || !ap_const_lv10_35.is_01())? sc_lv<10>(): sc_bigint<3>(ret_V_fu_33_p0.read()) * sc_biguint<10>(ap_const_lv10_35);
}

void fir::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V\" :  \"" << output_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_ap_vld\" :  \"" << output_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V\" :  \"" << input_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

