// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=22,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=227,HLS_SYN_LUT=235,HLS_VERSION=2019_1}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r,
        output_r_ap_vld,
        input_r
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] output_r;
output   output_r_ap_vld;
input  [31:0] input_r;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] shift_reg_address0;
reg    shift_reg_ce0;
reg    shift_reg_we0;
reg   [31:0] shift_reg_d0;
wire   [31:0] shift_reg_q0;
wire   [2:0] c1_address0;
reg    c1_ce0;
wire   [9:0] c1_q0;
wire   [2:0] i_fu_114_p2;
reg   [2:0] i_reg_163;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln16_fu_108_p2;
wire   [63:0] zext_ln18_1_fu_125_p1;
reg   [63:0] zext_ln18_1_reg_173;
wire   [31:0] mul_ln22_fu_130_p2;
reg   [31:0] mul_ln22_reg_183;
reg  signed [31:0] shift_reg_load_reg_188;
wire    ap_CS_fsm_state3;
reg   [9:0] c1_load_reg_193;
wire   [31:0] mul_ln19_fu_138_p2;
reg   [31:0] mul_ln19_reg_198;
wire    ap_CS_fsm_state4;
wire   [31:0] acc_fu_143_p2;
wire    ap_CS_fsm_state5;
reg   [31:0] acc_0_reg_85;
reg   [2:0] i_0_reg_97;
wire   [63:0] zext_ln18_fu_120_p1;
wire    ap_CS_fsm_state6;
wire  signed [31:0] mul_ln22_fu_130_p0;
wire  signed [9:0] mul_ln19_fu_138_p1;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

fir_shift_reg #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
shift_reg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(shift_reg_address0),
    .ce0(shift_reg_ce0),
    .we0(shift_reg_we0),
    .d0(shift_reg_d0),
    .q0(shift_reg_q0)
);

fir_c1 #(
    .DataWidth( 10 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c1_address0),
    .ce0(c1_ce0),
    .q0(c1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        acc_0_reg_85 <= acc_fu_143_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_0_reg_85 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_reg_97 <= i_reg_163;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_97 <= 3'd5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c1_load_reg_193 <= c1_q0;
        shift_reg_load_reg_188 <= shift_reg_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_163 <= i_fu_114_p2;
        zext_ln18_1_reg_173[2 : 0] <= zext_ln18_1_fu_125_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln19_reg_198 <= mul_ln19_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mul_ln22_reg_183 <= mul_ln22_fu_130_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        c1_ce0 = 1'b1;
    end else begin
        c1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_ap_vld = 1'b1;
    end else begin
        output_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_address0 = zext_ln18_1_reg_173;
    end else if (((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_address0 = 3'd0;
    end else if (((icmp_ln16_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_address0 = zext_ln18_fu_120_p1;
    end else begin
        shift_reg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln16_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        shift_reg_ce0 = 1'b1;
    end else begin
        shift_reg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_d0 = shift_reg_q0;
    end else if (((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_d0 = input_r;
    end else begin
        shift_reg_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        shift_reg_we0 = 1'b1;
    end else begin
        shift_reg_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln16_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_143_p2 = (mul_ln19_reg_198 + acc_0_reg_85);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign c1_address0 = zext_ln18_1_fu_125_p1;

assign i_fu_114_p2 = ($signed(i_0_reg_97) + $signed(3'd7));

assign icmp_ln16_fu_108_p2 = ((i_0_reg_97 == 3'd0) ? 1'b1 : 1'b0);

assign mul_ln19_fu_138_p1 = c1_load_reg_193;

assign mul_ln19_fu_138_p2 = ($signed(shift_reg_load_reg_188) * $signed(mul_ln19_fu_138_p1));

assign mul_ln22_fu_130_p0 = input_r;

assign mul_ln22_fu_130_p2 = ($signed(mul_ln22_fu_130_p0) * $signed('h35));

assign output_r = (acc_0_reg_85 + mul_ln22_reg_183);

assign zext_ln18_1_fu_125_p1 = i_0_reg_97;

assign zext_ln18_fu_120_p1 = i_fu_114_p2;

always @ (posedge ap_clk) begin
    zext_ln18_1_reg_173[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //fir
